### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by smlng** [smartuni/SmartWindow#14]
We found a major memory leak in your code
- you allocate memory [concat()](https://github.com/smartuni/SmartWindow/blob/master/RaspberryPi/Window_Controller/main_controller.cpp#L870) which is hardly ever freed afterwards: **very bad**
- `concat` is used twice in [tableName()](https://github.com/smartuni/SmartWindow/blob/master/RaspberryPi/Window_Controller/main_controller.cpp#L891), but at least one free() on the allocated memory is missing
- there is also a macro `CONCAT_TABLE` for the function `tableName()`, that is used multiple [times](https://github.com/smartuni/SmartWindow/blob/master/RaspberryPi/Window_Controller/main_controller.cpp#L359) for database queries, the allocated memory (2x) is never freed
- the longer your program runs the more mem is allocated and never free, at the end `malloc` will fail when system is out of memory resulting in a `segfault`

**Comment by pmlk** [comment]
addressed in commit (9a2752a58643ce871d229bd8049a5d5a4bf6dc96)

**Comment by smlng** [comment]
end of project
