### ISSUE TITLE
Ordner Struktur

### ISSUE THREAD

**Issue by pmlk** [smartuni/SmartWindow#9]
Da sich das Projekt langsam dem Ende nähert, schlage ich vor die Ordner Struktur etwas aufzuräumen:
- Documents
- RIOT Nodes
  - ...
- RaspberryPi
  - Webserver
  - MySQL
  - Window Controller

So ist deutlich ersichtlich welche Software wo zu installieren bzw. zu kompilieren ist. Die Namen sind so gewählt, dass alle bisherigen Ordner vorerst bestehen bleiben können. Nach und nach kann jeder seinen (endgültigen) Code in diese Ordner verschieben. Die Code-Leichen, Test-Programme usw. können langsam aus den alten Ordnern verschwinden und diese Ordner gelöscht werden.

**Comment by josephnoir** [comment]
This is a wonderful opportunity to add a `readme` file to the folders with a short description and possibly instructions on how to install / setup the module.

**Comment by shein318** [comment]
Mission Accomplished. The issue can be closed.
